### ISSUE TITLE
multiple repos/base images

### ISSUE THREAD

**Issue by modem7** [Al2Klimov/dockerhub-chainreactor#1]
Heya, 

What would be the best way to deal with multiple repos + base images? 

E.g. 

Telegraf
Grafana

With two different triggers. Would it be best to have multiple containers, or can we do multiple lines eg:

```
#log:
  # How verbosely to log (trace / debug / info / warn / error)
  #level: info
build:
  # When to build and deploy, crontab format
  every: '0 0 * * *'
hub:
  # URL to POST to ...
  # (Your repo - Builds - Configure Automated Builds - Build Triggers)
- post: https://hub.docker.com/api/build/v1/source/XXXX/trigger/YYYY/call/
  base:
  # ... on changes of these images:
  - telegraf:alpine
  # URL to POST to ...
  # (Your repo - Builds - Configure Automated Builds - Build Triggers)
- post: https://hub.docker.com/api/build/v1/source/XXXX/trigger/YYYY/call/
  base:
  # ... on changes of these images:
  - grafana:grafana
```

Thanks!

**Comment by Al2Klimov** [comment]
Hello @modem7!

You can have any number of images in `base`. Once any of them changes, the `post` URL is triggered.

Best,
AK

**Comment by modem7** [comment]
> 
> 
> Hello @modem7!
> 
> You can have any number of images in `base`. Once any of them changes, the `post` URL is triggered.
> 
> Best,
> AK

Ahhah, so would this work?

```
#log:
  # How verbosely to log (trace / debug / info / warn / error)
  level: info
build:
  # When to build and deploy, crontab format
  every: '0 0 * * *'
hub:
  # URL to POST to ...
  # (Your repo - Builds - Configure Automated Builds - Build Triggers)
#telegraf
- post: https://hub.docker.com/api/build/v1/source/xxxx/trigger/yyyy/call/
#grafana
- post: https://hub.docker.com/api/build/v1/source/xxxx/trigger/yyyy/call/
  base:
  # ... on changes of these images:
  - telegraf:alpine
  - grafana/grafana
```
